import React from 'react';
import { DesktopItem, FileType } from '../../types';
import { DESKTOP_ITEMS } from '../../constants';

interface SitemapViewerProps {
  onNavigate: (id: string) => void;
}

export const SitemapViewer: React.FC<SitemapViewerProps> = ({ onNavigate }) => {
  return (
    <div className="h-full bg-white dark:bg-zinc-950 overflow-y-auto p-8">
      <header className="mb-8 border-b border-black dark:border-white pb-4">
        <h1 className="text-3xl font-bold uppercase tracking-tighter text-black dark:text-white">
          System_Index / Sitemap
        </h1>
        <p className="text-zinc-500 font-mono text-sm mt-2">
            Index of all available content nodes. Optimized for crawling.
        </p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <section>
            <h2 className="text-sm font-bold uppercase tracking-widest text-red-600 mb-4 border-b border-zinc-200 dark:border-zinc-800 pb-2">
                Core Pages
            </h2>
            <ul className="space-y-4 font-mono text-sm">
                {DESKTOP_ITEMS.filter(i => i.type !== FileType.SITEMAP).map(item => (
                    <li key={item.id} className="group">
                        <a 
                            href={`#/${item.slug || item.id}`}
                            onClick={(e) => {
                                e.preventDefault();
                                onNavigate(item.id);
                            }}
                            className="block p-3 rounded border border-zinc-200 dark:border-zinc-800 hover:border-black dark:hover:border-white hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-all"
                        >
                            <span className="font-bold text-black dark:text-white block group-hover:underline">
                                {item.title}
                            </span>
                            <span className="text-xs text-zinc-500 block mt-1">
                                {item.seoDescription || 'Content node.'}
                            </span>
                        </a>
                    </li>
                ))}
            </ul>
        </section>

        <section>
            <h2 className="text-sm font-bold uppercase tracking-widest text-red-600 mb-4 border-b border-zinc-200 dark:border-zinc-800 pb-2">
                Blog Archives
            </h2>
            <ul className="space-y-4 font-mono text-sm">
                {DESKTOP_ITEMS.find(i => i.id === 'blog')?.blogPosts?.map(post => (
                     <li key={post.id}>
                        <a 
                            href={`#/blog/${post.id}`}
                             onClick={(e) => {
                                e.preventDefault();
                                onNavigate('blog');
                                // In a real app this would deep link, handled via hash router in App.tsx
                            }}
                            className="block p-3 rounded border border-zinc-200 dark:border-zinc-800 hover:border-black dark:hover:border-white transition-all"
                        >
                             <span className="font-bold text-black dark:text-white block">
                                {post.title}
                            </span>
                            <div className="flex gap-2 text-xs text-zinc-500 mt-1">
                                <span>{post.date}</span>
                                <span>•</span>
                                <span>{post.tags.join(', ')}</span>
                            </div>
                        </a>
                     </li>
                ))}
            </ul>
        </section>
      </div>
      
      <footer className="mt-12 text-xs text-zinc-400 font-mono border-t border-zinc-200 dark:border-zinc-800 pt-4">
        Generated by Portfolio OS Kernel v2.1. Valid HTML5.
      </footer>
    </div>
  );
};